[build-system]
requires = ["setuptools", "wheel", "Cython>=3.0.0"]

[tool.black]
line-length = 120
[tool.ruff]
line-length = 120
src = ["src"]
respect-gitignore = true
select = [
    "E", # pycodestyle
    "F", # pyflakes,
    "D", # pydocstyle,
]
[tool.ruff.pydocstyle]
convention = "google"
