# This workflow will use Nox to run tests and lint for the supported Python versions, and upload the test coverage data.

name: Build & Test

on:
    push:
        branches:
            - main
            - release/*
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: excitedleigh/setup-nox@v2.0.0
            - run: nox
            - name: Report to Coveralls
              uses: coverallsapp/github-action@v2
              with:
                  file: ".coverage"
