# This workflow will install Python dependencies, run tests and lint for the supported Python versions.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python.

name: Build & Test 2

on:
    push:
        branches:
            - main
            - release/*
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: excitedleigh/setup-nox@v2.0.0
            - run: nox
            - name: Report to Coveralls
              uses: coverallsapp/github-action@v2
              with:
                  file: ".coverage"
