# This workflow builds Sphinx documentation and deploys it to GitHub Pages.

name: Publish documentation

on:
    push:
        branches: [main] # branch to trigger deployment
    release:
        types: [published] # releases trigger deployment as well

jobs:
    pages:
        runs-on: ubuntu-latest
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        permissions:
            pages: write
            id-token: write
        steps:
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install poetry
                  poetry install --with docs
            - id: deployment
              uses: sphinx-notes/pages@v3
              with:
                  pyproject_extras: "docs"
