# This workflow checks out a new release and publishes it to PyPI using Poetry.

name: Publish Package

# Controls when the workflow will run
on:
    # Workflow will run when a release has been published for the package
    release:
        types:
            - published

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    build_platform_specific_wheels:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [macos-latest, windows-latest] # important: if adding OSes here, also download them in build_and_publish_as_package

        steps:
            - name: Setup MinGW on Windows
              if: matrix.os == 'windows-latest'
              uses: egor-tensin/setup-mingw@v2
              with:
                  platform: x64
            - uses: actions/checkout@v3
            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.11"
            - name: Setup Poetry
              uses: Gr1N/setup-poetry@v8
            - name: Build wheel distribution
              run: |
                  poetry install
                  poetry build -f wheel
                  ls ./dist
            - name: Upload the built wheel distribution
              uses: actions/upload-artifact@v3
              with:
                  name: ${{ matrix.os }}
                  path: ./dist/*.whl
                  if-no-files-found: error

    build_and_publish_as_package:
        name: Build the wheel and source on Ubuntu and upload release to PyPI
        needs: [build_platform_specific_wheels]
        runs-on: ubuntu-latest
        environment:
            name: pypi
            url: https://pypi.org/p/python-constraint2
        permissions:
            id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
        steps:
            - uses: actions/checkout@v3
            - name: Download the macOS wheel
              uses: actions/download-artifact@v3
              with:
                  name: macos-latest
                  path: ./dist
            - name: Download the Windows wheel
              uses: actions/download-artifact@v3
              with:
                  name: windows-latest
                  path: ./dist
            - name: Check whether remotely built distributions are available
              run: ls ./dist
            - name: Build the Linux wheel and source distribution
              uses: actions/checkout@v3
            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.11"
            - name: Setup Poetry
              uses: Gr1N/setup-poetry@v8
            - name: Build wheel and source distributions
              run: |
                  poetry install
                  poetry build
                  ls ./dist
            - name: Publish package distributions to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
