# This workflow checks out a new release and publishes it to PyPI using Poetry.

name: Publish Package

# Controls when the workflow will run
on:
    # Workflow will run when a release has been published for the package
    release:
        types:
            - published

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    build_platform_specific_wheels:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest] # important: if adding OSes here, also download them in build_and_publish_as_package
                pyversion: ["3.10", "3.11"]
                exclude:
                    - os: ubuntu-latest
                      pyversion: "3.11" # exclude because we already use this OS and version for building the source package

        steps:
            - uses: actions/checkout@v3
            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.pyversion }}
            - name: Setup Poetry
              uses: Gr1N/setup-poetry@v8
            - name: Build wheel distribution
              run: |
                  poetry install
                  poetry build -f wheel
                  ls ./dist
            - name: Upload the built wheel distribution
              uses: actions/upload-artifact@v3
              with:
                  name: ${{ matrix.os }}_${{ matrix.pyversion }}
                  path: ./dist/*.whl
                  if-no-files-found: error

    build_and_publish_as_package:
        name: Build the wheel and source on Ubuntu and upload release to PyPI
        needs: [build_platform_specific_wheels]
        runs-on: ubuntu-latest
        environment:
            name: pypi
            url: https://pypi.org/p/python-constraint2
        permissions:
            id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
        steps:
            - uses: actions/checkout@v3
            - name: Download all platform-specific wheels to the `temp_dist` folder
              uses: actions/download-artifact@v3
              with:
                  path: ./temp_dist
            - name: Unpack the remotely built wheels to the `dist` folder
              run: | # searches for wheel files in all subdirectories and moves the files to ./dist
                  ls ./temp_dist
                  mkdir -p ./dist
                  ls ./temp_dist/macos-latest_3.11
                  find ./temp_dist -name '*.whl' -exec mv {} ./dist \;
                  rm -rf ./temp_dist
            - name: Build the Linux wheel and source distribution
              uses: actions/checkout@v3
            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.11"
            - name: Setup Poetry
              uses: Gr1N/setup-poetry@v8
            - name: Build wheel and source distributions
              run: |
                  poetry install
                  poetry build
                  ls ./dist
            - name: Publish package distributions to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
