# This workflow checks out a new release and publishes it to PyPI using Poetry.

name: Publish Package

# Controls when the workflow will run
on:
    # Workflow will run when a release has been published for the package
    release:
        types:
            - published

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Build and publish to PyPI
              uses: JRubics/poetry-publish@v1.17
              with:
                  pypi_token: ${{ secrets.PYPI_API_TOKEN }}
