# This workflow checks out a new release and publishes it to PyPI using Poetry.

name: Publish Package

# Controls when the workflow will run
on:
    # Workflow will run when a release has been published for the package
    release:
        types:
            - published

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    publish:
        name: Upload release to PyPI
        runs-on: ubuntu-latest
        environment:
            name: pypi
            url: https://pypi.org/p/python-constraint2
        permissions:
            id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                  python-version: "3.11"
            - uses: Gr1N/setup-poetry@v8
            - run: |
                  poetry install
                  poetry build
                  ls
                  ls ./dist
            - name: Publish package distributions to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
